<?= $this->doctype() ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?= $this->headTitle('MOGO')->setSeparator(' - ')->setAutoEscape(false) ?>

		<?= $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
			->prependStylesheet($this->basePath('css/style.css'))
			->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
			->prependStylesheet($this->basePath('css/bootstrap.min.css'))
		?>

		<!-- Scripts -->
		<?= $this->headScript()
			->prependFile($this->basePath('js/bootstrap.min.js'))
			->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
		?>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?= $this->url('home') ?>">
						<img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>
						&nbsp;MOGO
					</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="<?=(!$this->action?"active":"")?>"><a href="<?= $this->url('home') ?>">Home</a></li>
<?php
$a=[
	"teams"=>"Teams"
	,"matches"=>"Matches"
	,"playoff"=>"Play Off"
	,"final"=>"Final"
];
foreach($a as $i=>$j){
?>
						<li class="<?=($this->action==$i?"active":"")?>"><a href="<?=$this->url("application",["action"=>$i])?>"><?=$j?></a></li>
<?php }?>
					</ul>
					<ul class="nav navbar-nav navbar-right">
				        <li class="<?=($this->action=="teams"?"active":"")?>"><a href="<?=$this->url("application",["action"=>"truncate"])?>">Erase DB</a></li>
				    </ul>
				</div>
			</div>
		</nav>
		<div class="container">
			<?= $this->content ?>
			<hr>
			<footer>
				<p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
			</footer>
		</div>
		<?= $this->inlineScript() ?>
	</body>
</html>
