	<div class="row">
		<div class="col-md-3">
			<table class="table table-striped table-hover">
				<tr>
					<th>Group</th>
					<th>Team1</th>
					<th>Team2</th>
					<th>Score</th>
				</tr>
<?php 
$i=0;
foreach($this->matches as $r) {
	$i++;
	$t1=null;
	$t2=null;
	foreach($this->teams as $t) 
	{
		$t1=$t->id==$r->team1?$t:$t1;
		$t2=$t->id==$r->team2?$t:$t2;
	}
?>
				<tr>
					<td><?=$t1?$t1->group:""?></td>
					<td nowrap><?=$t1?$t1->name:""?></td>
					<td nowrap><?=$t2?$t2->name:""?></td>
					<td nowrap><?=$r->score1?>:<?=$r->score2?></td>
				</tr>
<?php if($i%8==0&&$this->matches[count($this->matches)-1]!=$r){?>
			</table>
		</div>
		<div class="col-md-3">
			<table class="table table-striped table-hover">
				<tr>
					<th>Group</th>
					<th>Team1</th>
					<th>Team2</th>
					<th>Score</th>
				</tr>
<?php 
	}
}?>
			</table>
		</div>
	</div>

	<h2>Group Results</h2>
	<div class="row">
		<div class="col-md-3">
			<table class="table table-striped table-hover">
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Group</th>
					<th>Score</th>
				</tr>
<?php 
$i=0;
foreach($this->teams as $r) {
	$i++;
	$score=0;
	foreach($this->matches as $t) 
	{
		$score+=$r->id==$t->team1?$t->score1:0;
		$score+=$r->id==$t->team2?$t->score2:0;
	}
?>
				<tr>
					<td><?=$r->id?></td>
					<td><?=$r->name?></td>
					<td><?=$r->group?></td>
					<td><?=$score?></td>
				</tr>
<?php if($i%4==0&&$this->teams[count($this->teams)-1]!=$r){?>
			</table>
		</div>
		<div class="col-md-3">
			<table class="table table-striped table-hover">
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Group</th>
					<th>Score</th>
				</tr>
<?php 
	}
}?>
			</table>
		</div>
	</div>