<div class="row">
	<div class="col-md-6">
		<table class="table table-striped table-hover">
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Group</th>
				<th>Created</th>
			</tr>
<?php 
for($i=0;$i<count($this->teams);$i++) {
$r=$this->teams[$i];
?>
			<tr>
				<td><?=$r->id?></td>
				<td><?=$r->name?></td>
				<td><?=$r->group?></td>
				<td><?=$r->created?></td>
			</tr>
<?php if(($i+1)%8==0&&$this->teams[count($this->teams)-1]!=$r){?>
		</table>
	</div>
	<div class="col-md-6">
		<table class="table table-striped table-hover">
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Group</th>
				<th>Created</th>
			</tr>
<?php 
}
}?>
		</table>
	</div>
</div>